# Configuration of Hugo
# Title of your site
title = "Ligo Theme"
# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"
#Use an subtheme to override the base theme --> theme = ["abt-hugo-bulma-subtheme","abt-hugo-bulma"]
theme = ["ligo"]
############################
## Advanced options below ##
############################
# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687
summaryLength = 30  # Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = false # can have performance isues for true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
# more info about canonifyurls : https://gohugo.io/content-management/urls/#canonicalization
canonifyurls = true
[permalinks]
  # If only creating events which are talks, we can optimize event URLs for talks.
  # event = "/event/:slug/"
  # product = "/product/:slug/"
  # Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular
  # tags = "/tags/:slug/"
  # categories = "/categories/:slug/"
[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]
[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]
[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure the Markdown renderer.
# https://gohugo.io/news/0.60.0-relnotes/ - for inline shortcode
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true 
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "Lanczos"
  quality = 75
  anchor = "Smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  # product_category = "product_categories"
# If you do not want Hugo to create any taxonomies, set disableKinds in your site config to the following
# disableKinds = ["taxonomy", "term"]

# Related content.
[related]
  threshold = 80.0
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "title"
    weight = 60.0
  [[related.indices]]
    name = "summary"
    weight = 50.0
  [[related.indices]]
    name = "tags"
    weight = 80.0
  [[related.indices]]
    name = "categories"
    weight = 70.0
  [[related.indices]]
    name = "authors"
    weight = 20.0
    
[module]
[module.hugoVersion]
extended = true
min = "0.117.0"
# 1. npm install  -> 2. mount files from node_modules
[[module.mounts]]
    source = "node_modules/@fontsource/playfair-display/files"
    target = "static/webfonts"
[[module.mounts]]
    source = "node_modules/@fontsource/roboto/files"
    target = "static/webfonts"
[[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"
[[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/scss"
    target = "assets/scss/fonts/fontawesome"
# npm install bulma scss
[[module.mounts]]
    source = "node_modules/bulma/sass"
    target = "assets/scss/bulma"
# npm install bulma-carousel css + js -> mount
[[module.mounts]]
    source = "node_modules/bulma-carousel/dist/css"
    target = "assets/css/active"
[[module.mounts]]
    source = "node_modules/bulma-carousel/dist/js"
    target = "assets/js/active"
# vanilla-cookieconsent - css + js
[[module.mounts]]
    source = "node_modules/vanilla-cookieconsent/dist"
    target = "assets/css/active"
[[module.mounts]]
    source = "node_modules/vanilla-cookieconsent/dist"
    target = "assets/js/active"
####### HUGO MODULES (in future)
## BULMA Framework 
# [[module.imports]]
#   path = "github.com/jgthms/bulma"
#   disable = false
#   [[module.imports.mounts]]
#     source = "sass"
#     target = "assets/scss/bulma/sass"
## Bulma Extensons -> Carousel !!! DISABLED - does not download the right code !!!
# [[module.imports]]
# path = "github.com/Wikiki/bulma-carousel"
# disable = true
#   [[module.imports.mounts]]
#     source = "dist/css"
#     target = "assets/css/active"
#   [[module.imports.mounts]]
#     source = "dist/js"
#     target = "assets/js/active"
## FONTS font-awesome !!! DISABLED - does not download the right code !!!
# [[module.imports]]
# path = "https://github.com/FortAwesome/Font-Awesome"
# disable = true
#   [[module.imports.mounts]]
#     source = "webfonts"
#     target = "static/webfonts"
#   [[module.imports.mounts]]
#     source = "scss"
#     target = "assets/scss/fonts/fontawesome"
## FONTS fontsource !!! DISABLED - download the whole repo with all the google fonts !!!
# [[module.imports]]
# path = "github.com/fontsource/font-files"
# disable = true
# [[module.imports.mounts]]
# source = "fonts/google/roboto/scss"
# target = "assets/scss/fonts/roboto"
# [[module.imports.mounts]]
# source = "fonts/google/roboto/files"
# target = "static/webfonts"
# [[module.imports.mounts]]
# source = "fonts/google/playfair-display"
# target = "assets/scss/fonts/playfair-display"
# [[module.imports.mounts]]
# source = "files"
# target = "static/webfonts"