# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10
[[main]]
  name = "About"
  url = "/about/"
  weight = 20
[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 30
[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 40


# Link to a PDF / DOC  -> To enable, copy your PDF / DOC to `static/media/doc.pdf` and uncomment the lines below.
# [[main]]
#    name = "DOC"
#    url = "media/doc.pdf"
#    weight = 70
[[social]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/"
    pre = "<i class='fa fa-github'></i>"
[[social]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-facebook'></i>"
[[social]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-twitter'></i>"
[[social]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-envelope'></i>"